name: "Continuous Integration Workflow"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.3.4

      - name: "Run Tests"
        run: make test

      - name: "Build Production Image"
        run: make build-production VERSION=build-${GITHUB_SHA}
