name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Set up PDM"
        run: |
          pip install --upgrade pip==23.2.1
          pip install --user pdm==2.9.0
          pdm install

      - name: "Test Cookiecutter"
        run: make test
